run all tests and return cleaner output

diff --git a/tests/do_tests b/tests/do_tests
--- a/tests/do_tests
+++ b/tests/do_tests
@@ -13,3 +13,4 @@ done
 
 echo "OK: ${#passed[@]}"
 echo "failed(${#failed[@]}): ${failed[@]}"
+exit "${#failed}"
